/**
 * @format
 */

export const map = [
  [
    {
      id: 1,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 2,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 3,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 4,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 5,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 6,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 7,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 8,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 21,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 22,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 23,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 24,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 25,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 26,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 27,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 28,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 31,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 32,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 33,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 34,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 35,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 36,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 37,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 38,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 41,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 42,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 43,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 44,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 45,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 46,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 47,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 48,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 51,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 52,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 53,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 54,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 55,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 56,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 57,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 58,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 61,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 62,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 63,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 64,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 65,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 66,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 67,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 68,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 71,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 72,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 73,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 74,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 75,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 76,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 77,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 78,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 81,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 82,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 83,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 84,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 85,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 86,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 87,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 88,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 91,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 92,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 93,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 94,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 95,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 96,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 97,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 98,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 111,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 112,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 113,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 114,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 115,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 116,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 117,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 118,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 121,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 122,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 123,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 124,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 125,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 126,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 127,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 128,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 131,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 132,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 133,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 134,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 135,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 136,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 137,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 138,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 141,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 142,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 143,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 144,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 145,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 146,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 147,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 148,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 151,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 152,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 153,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 154,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 155,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 156,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 157,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 158,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 161,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 162,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 163,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 164,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 165,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 166,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 167,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 168,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
  [
    {
      id: 171,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'town',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 172,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 173,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'village',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 174,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 175,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 176,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 177,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
    {
      id: 178,
      type: 'terra',
      owner: null,
      locality: {
        id: 1,
        type: 'terra',
        name: 'Новосиб',
      },
      resources: [{id: 123, type: 'wood', count: 100}],
    },
  ],
];
